### PR TITLE
Added options for cloud section in devops page

### PR DESCRIPTION
**Pull request by Akshay9607**
## 198

This PR fixes the following issues:

#add other option in cloud section of devops page

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots and video
image

### CODE REVIEW

**Review by mnnkhndlwl — CHANGES_REQUESTED** [review]
have u made a separate page for aws

**Comment by pradeeptosarkar** [comment]
damn

**Comment by Akshay9607** [comment]
is it okay if i do that now ?

**Comment by pradeeptosarkar** [comment]
@Akshay9607 yes

**Comment by Akshay9607** [comment]
okay , i'll do that now

**Comment by Akshay9607** [comment]
Done, you can review and merge now.

**Pull request merged**
