### PR TITLE
Added separate Firebase page under webd

### LINKED ISSUE #258: [Feature]: separate dedicated page for firebase
### Is your feature request related to a problem? Please describe.

separate dedicated page for firebase under webd is missing.

### Describe the solution you'd like

Can add the separate page for firebase

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tamago01**
- This PR fixes the absence of dedicated Firebase page under webd section.

- This PR adds the separate Firebase page including all the related contents.

- Fixes #258  separate dedicated page for firebase 

- Before:
image

- After: 
image

### CODE REVIEW

**Comment by pradeeptosarkar** [comment]
@tamago01 some build checks are failing. Please resolve. You can run the build command locally to verify what is the issue

**Review by pradeeptosarkar — CHANGES_REQUESTED** [review]
@tamago01 some build checks are failing. Please resolve. You can run the build command locally to verify what is the issue

**Comment by mnnkhndlwl** [comment]
replace package-lock.json from your commit with that in master branch

**Comment by tamago01** [comment]
@pradeeptosarkar @mnnkhndlwl  please check now.

**Review by pradeeptosarkar — APPROVED** [review]

**Comment by tamago01** [comment]
Please label this PR hacktoberfest too :D @pradeeptosarkar

**Comment by pradeeptosarkar** [comment]
@tamago01 done :)

**Pull request merged**
