### PR TITLE
fixed issue #381

### PR DESCRIPTION
**Pull request by sajithsojan**
changed the title card coding to python,
added python resources page with courses, coding platforms and youtube videos.

## Added resources for python
 
This PR fixes the following issues:

#example

->changed coding title to python
->added new page for python
->added resources for python learning

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots and video
pythonresourcespt3
coding to python
pythonresourcespt1
pythonresourcespt2

Add all the screenshots and a video which support your changes

### CODE REVIEW

**Review by pradeeptosarkar — APPROVED** [review]

**Comment by pradeeptosarkar** [comment]
@sajithsojan kindly look at it, the build checks are failing. You may run npm build locally to check the build

**Comment by sajithsojan** [comment]
ok let me check

**Comment by sajithsojan** [comment]
> @sajithsojan kindly look at it, the build checks are failing. You may run npm build locally to check the build

i just updated the npm and run the build it works

**Comment by sajithsojan** [comment]
> > @sajithsojan kindly look at it, the build checks are failing. You may run npm build locally to check the build
> 
> i just updated the npm and run the build it works

Screenshot 2023-10-18 101819

**Comment by pradeeptosarkar** [comment]
@sajithsojan you need to commit the changes also

**Comment by pradeeptosarkar** [comment]
@sajithsojan failing again

**Comment by mnnkhndlwl** [comment]
@sajithsojan check the details your package.json or package-lock.json is not in sync with that of master branch

**Pull request closed without merging**
