### PR TITLE
changed the styling of resource page

### LINKED ISSUE #319: [Feature]: Beautify resources page
### Is your feature request related to a problem? Please describe.

change the current theme of the resources page you can take inspiration from programs page and teams page

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tamago01**
- This PR addresses the plain UI of Resource page.
- This PR changes the UI and adds the additional touch to the page.
- Fixes #319 
- Before:
image

- After:
image

### CODE REVIEW

**Comment by mnnkhndlwl** [comment]
it would be better if you show three cards for row

**Comment by tamago01** [comment]
image
If we put 3 cards in a row, the description will be like this. Do you still want to display 3 cards?

**Comment by tamago01** [comment]
done
image

**Comment by pradeeptosarkar** [comment]
> * This PR addresses the plain UI of Resource page.
> * This PR changes the UI and adds the additional touch to the page.
> * Fixes [[Feature]: Beautify resources page #319](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/issues/319)
> * Before:
>   image
> * After:
>   image

@tamago01 can we do it this way only, as 3 cards per row is looking ugly

**Comment by tamago01** [comment]
please check once

**Comment by pradeeptosarkar** [comment]
@tamago01 the build check is failing pls have a look

**Comment by tamago01** [comment]
image
The only warnings that I'm getting on my localhost are these, everything else is working perfectly. Perhaps the problem occurred due to my previous commits?

**Comment by mnnkhndlwl** [comment]
your package-lock.json is probably not in sync with the  project

**Comment by tamago01** [comment]
Done. should work now. 
Also, thanks for the opportunities @mnnkhndlwl  and @pradeeptosarkar. This year was my first ever Hacktoberfest participation and I surely learned a lot working here in your issues.

**Review by pradeeptosarkar — APPROVED** [review]

**Comment by pradeeptosarkar** [comment]
thanks for contributing @tamago01 , you have been awesome :)

**Pull request merged**
