### PR TITLE
Added dedicated Nodejs page under webd

### LINKED ISSUE #235: [Feature]: make a dedicated page for nodejs under webd page
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tamago01**
- This PR fixes the absence of dedicated Nodejs page under webd section.
- This PR adds the dedicated Nodejs page including all the necessary contents.
- Fixes #235
- Earlier it was like this: 
image

- Now it looks like this:
image

### CODE REVIEW

**Comment by pradeeptosarkar** [comment]
@tamago01 the build checks are failing kindly have a look

**Comment by mnnkhndlwl** [comment]
you can try deleting  your package-lock.json

**Comment by tamago01** [comment]
@mnnkhndlwl  @pradeeptosarkar could you please try now? I have removed package-lock.json file from my end.

**Comment by mnnkhndlwl** [comment]
Please try by including package-lock.json from master branch and then push a new commit

**Comment by tamago01** [comment]
@mnnkhndlwl Done. Please check. Also, what is actually happening? Did I do something wrong? This is my first time participating on H-fest so please forgive me.

image

**Comment by mnnkhndlwl** [comment]
now it has passed all the checks

**Review by mnnkhndlwl — APPROVED** [review]

**Comment by tamago01** [comment]
@mnnkhndlwl Thanks for the opportunity. Also, could you check this #54?

**Pull request merged**
