### PR TITLE
Removed unecessary \

### PR DESCRIPTION
**Pull request by keshav39**
## Changes proposed

- Team page link on hero's team section was not reflected in the merge or was overwritten on another's merge so recommitted that.
- unnecessary escape sequences in the constants/constants.js file's links for member's profiles

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots and video

image

### CODE REVIEW

**Comment by pradeeptosarkar** [comment]
@keshav39 merge conflicts..! pro tip: main bhi boht baar fasa hu iss exact file mein isliye isko haath hi nahi lagata 🤣

**Comment by keshav39** [comment]
see if the conflict was resolved?

**Comment by keshav39** [comment]
## Changes proposed for the last 3 commits

- made the navbar stick to the top added padding to all containers to prevent overlapping of content

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots and video

image

**Comment by pradeeptosarkar** [comment]
yep. merged

**Pull request merged**
