### PR TITLE
fix: footer displayed twice

### PR DESCRIPTION
**Pull request by nikhilgarg26**
## Fixes Issue

This PR fixes the following issues: #311 

Footer component deleted

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by pradeeptosarkar — CHANGES_REQUESTED** [review]
@nikhilgarg26 pls check the builds are failing

**Comment by nikhilgarg26** [comment]
@pradeeptosarkar could you please help why the build error is coming, can't figure it out

**Comment by pradeeptosarkar** [comment]
@nikhilgarg26 umm the issue mostly arises when the package-lock.json is not in sync. You may copy the package lock as well as package file from the master and paste in your version then push the commit

**Comment by nikhilgarg26** [comment]
> @nikhilgarg26 umm the issue mostly arises when the package-lock.json is not in sync. You may copy the package lock as well as package file from the master and paste in your version then push the commit

Thanks for the solution

**Review by pradeeptosarkar — APPROVED** [review]

**Pull request merged**
