### PR TITLE
[feature] : removed java, kotlin, cross plateform and added react native in andriod page

### PR DESCRIPTION
**Pull request by Rehan52004**
Java, Kotlin, Cross Plateform removed and React Natice added.

fixes : #144 

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ x] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

Screenshot 2023-10-02 195916

### CODE REVIEW

**Comment by pradeeptosarkar** [comment]
@Rehan52004 pls resolve the merge conflicts

**Review by mnnkhndlwl — CHANGES_REQUESTED** [review]
you haven't made a separate page for react native

**Comment by Rehan52004** [comment]
Ohh.. I understand.
But one more doubt that is, What will be written in  React native page.

**Comment by mnnkhndlwl** [comment]
take example from other pages like there are pages for javascript in webd and you can take content from internet

**Comment by Rehan52004** [comment]
Seprate React Native page added.

Check........!

**Comment by pradeeptosarkar** [comment]
@Rehan52004 pls look into the merge conflicts

**Pull request merged**
